### ISSUE TITLE
Bug on NZB.su Details Page- Adds 2 Download Icons On Tab Switching

### ISSUE THREAD

**Issue by war59312** [hpsu/nzbget-chrome#49] opened 2016-03-12 01:46 UTC
Hi,

Thanks a lot.. Great extension.

Small bug..

On nzb.su details page. 

Each time you change tabs (details, media info, etc.) and switch back to details tab.

2 download icon gets added to the page.

Should only be a single download icon of course.

Should not be adding another download icon just because I switch tabs on the page.

Thanks,

Will

**Comment by hpsu** [comment] 2016-03-12 08:08
Duplicate of #39 Already fixed in dev version.

**Closed by hpsu** 2016-03-12 08:08 UTC
Labels: duplicate

**Comment by war59312** [comment] 2016-03-12 13:17
Whoops and forgot I already had told you.

Sorry.
