### ISSUE TITLE
Initial page loads without stylesheet

### ISSUE THREAD

**Issue by dgcurtis** [hpsu/nzbget-chrome#64] opened 2017-07-03 00:16 UTC
It's a minor thing but whenever I click on the icon to open up the nzbget web page, I always have to add a / to the end of the url.  Otherwise it doesn't display properly.

**Comment by dgcurtis** [comment] 2017-07-17 13:35
So it's not a / that needs appending but for some reason, I always have to reload the page.  The initial page load seems to be omitting the stylesheet.  Once it reload the page, it looks normal

**Comment by hpsu** [comment] 2017-07-17 14:02
This is a duplicate of #62

**Closed by hpsu** 2017-07-17 14:02 UTC
